# Generated by Django 5.0.1 on 2024-02-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': "Task's Photo Table", 'verbose_name_plural': "Task's Photo Table"},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Tasks Table', 'verbose_name_plural': 'Tasks Table'},
        ),
    ]
