# Generated by Django 5.0.1 on 2024-02-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_photos_options_alter_tasks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['priority'], 'verbose_name': 'Tasks Table', 'verbose_name_plural': 'Tasks Table'},
        ),
    ]
