# Generated by Django 5.0.1 on 2024-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-priority'], 'verbose_name': 'Tasks Table', 'verbose_name_plural': 'Tasks Table'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('a', 'Low'), ('b', 'Medium'), ('c', 'High')], max_length=20),
        ),
    ]
